"""Constants for the Frosted Glass Manager integration."""

DOMAIN = "frosted_glass_manager"

# Default values (Tvoja pôvodná Fialová)
DEFAULT_LIGHT_PRIMARY = [106, 116, 211]
DEFAULT_LIGHT_BG = "https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-light-background.jpg"

DEFAULT_DARK_PRIMARY = [106, 116, 211]
DEFAULT_DARK_BG = "https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-dark-background.jpg"

THEME_FILENAME = "frosted_glass_custom.yaml"

THEME_TEMPLATE = """
# Frosted Glass Custom
# Auto-generated by Frosted Glass Manager based on v1.2.2

Frosted Glass Custom:
  modes:
    light:
      card-mod-theme: "Frosted Glass Custom"

      # =========================
      # HEADER (Top Bar)
      # =========================
      app-header-backdrop-filter: 'blur(6px) saturate(1.2)'
      app-header-background-color: 'rgba(234, 235, 238, 0.1)'
      app-header-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.95)'
      app-header-edit-background-color: 'rgba(255, 255, 255, 0.8)'
      app-header-edit-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.98)'
      app-theme-color: 'rgb(91, 138, 168)'

      # =========================
      # SIDEBAR / DRAWER
      # =========================
      sidebar-background-color: 'rgba(254, 244, 242, 0.7)'
      sidebar-icon-color: 'rgba(__LIGHT_TEXT_RGB__, 0.6)'
      sidebar-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.8)'
      sidebar-selected-icon-color: 'rgba(__LIGHT_TEXT_RGB__, 0.95)'
      sidebar-selected-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.98)'

      # Sidebar blur (card-mod-root section at end handles blur effect!)

      # =========================
      # DIALOGS
      # =========================
      ha-dialog-surface-backdrop-filter: 'blur(8px)'                                   
      ha-dialog-surface-background: 'rgba(234, 235, 238, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.15)'
      paper-dialog-background-color: 'rgba(234, 235, 238, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.6)'

      # =========================
      # CARDS / CARD-MOD
      # =========================
      card-mod-card: |
        /* Base reset */
        ha-card {
          background: transparent;
          backdrop-filter: none;
          -webkit-backdrop-filter: none;
        }

        /* Glass layer */
        ha-card::before {
          content: '';
          position: absolute;
          inset: 0;
          background: var(--ha-card-glass-tint, rgba(255, 255, 255, 0.08));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          z-index: -1;
          pointer-events: none;
          border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow,
            3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset,
            -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset,
            0 0 8px 1px rgba(255, 255, 255, 0.10) inset,
            0 0 2px 0 rgba(0, 0, 0, 0.10)
          );
        }

        /* Headings + Glance (kept as your exclusions) */
        :host(hui-heading-card) ha-card,
        :host(hui-glance-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }
        :host(hui-heading-card) ha-card::before,
        :host(hui-glance-card) ha-card::before {
          content: none !important;
        }

        /* Data tables */
        .mdc-data-table {
          background: none !important;
        }
        .mdc-data-table__header-cell {
          background: rgba(255, 255, 255, 0.1) !important;
          backdrop-filter: var(--ha-card-backdrop-filter) !important;
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter) !important;
          box-shadow: var(--ha-card-glass-inset-shadow) !important;
        }

        /* Markdown card with text_only */
        :host(.text-only) ha-card,
        :host(.text-only) ha-card::before,
        ha-card.text-only,
        ha-card.text-only::before {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          content: none !important;
        }

        /* Mushroom title card (no background or blur) */
        :host(mushroom-title-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
        }
        :host(mushroom-title-card) ha-card::before {
          content: none !important;
        }

        /* === Prevent frosted glass from applying to bubble cards === */
        :host(.type-custom-bubble-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          border-radius: 0px !important;
        }
        :host(.type-custom-bubble-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }

        /* === Prevent frosted glass from applying to mushroom-chips-card outer container === */
        :host(mushroom-chips-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
        }
        :host(mushroom-chips-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }
        
        /* === FIX: Navbar Card - Force transparency via CSS override === */
        navbar-card { --navbar-background-color: transparent !important; }
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }

      # =========================
      # CARD-MOD-ROOT GLOBAL CSS
      # =========================
      card-mod-root: |
       :host {
        --ha-card-background: rgba(242, 245, 255, 0.1);
        --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.15);
        --ha-card-border-width: 0.5px;
        --ha-card-border-color: rgba(255, 255, 255, 0.3);
        --ha-card-backdrop-filter: blur(8px) saturate(1.2);

        /* Glass system tokens */
        --ha-card-glass-tint: rgba(255, 255, 255, 0.08);
        --ha-card-glass-inset-shadow:
          3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset,
          -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset,
          0 0 8px 1px rgba(255, 255, 255, 0.10) inset,
          0 0 2px 0 rgba(0, 0, 0, 0.10);
       
        /* Tokens (Dynamic) */
        --token-rgb-primary: __LIGHT_PRIMARY_RGB__;
        --token-rgb-black: 0, 0, 0;
        --token-rgb-white: 240, 243, 255;
        --token-rgb-purple: 129, 45, 250;
        --token-rgb-pink: 204, 0, 136;
        --token-rgb-red: 204, 0, 51;
        --token-rgb-deep-purple: 98, 0, 234;
        --token-rgb-indigo: 48, 63, 159;
        --token-rgb-blue: 33, 150, 243;
        --token-rgb-light-blue: 3, 169, 244;
        --token-rgb-cyan: __LIGHT_PRIMARY_RGB__;
        --token-rgb-teal: __LIGHT_PRIMARY_RGB__;
        --token-rgb-green: 56, 142, 60;
        --token-rgb-light-green: 139, 195, 74;
        --token-rgb-lime: 205, 220, 57;
        --token-rgb-yellow: 250, 183, 0;
        --token-rgb-amber: 255, 193, 7;
        --token-rgb-orange: 255, 158, 0;
        --token-rgb-deep-orange: 255, 87, 34;
        --token-rgb-brown: 121, 85, 72;
        --token-rgb-grey: 103, 104, 119;
        --token-rgb-blue-grey: 96, 125, 139;
        --token-rgb-disabled: 189, 189, 189;
        --token-rgb-state-inactive: 176, 190, 197;

        --token-color-primary: rgb(var(--token-rgb-primary));
        --token-color-primary-light: rgb(167 182 199);
        --token-color-accent: rgb(var(--token-rgb-teal));
        --token-color-disabled: rgb(173 176 184);
        --token-color-feedback-info: rgb(__LIGHT_PRIMARY_RGB__);
        --token-color-feedback-warning: rgb(255, 219, 117);
        --token-color-feedback-error: rgb(234, 114, 135);
        --token-color-feedback-success: rgb(118, 214, 152);
        --token-color-icon-primary: rgba(__LIGHT_TEXT_RGB__, 0.95);
        --token-color-icon-secondary: rgba(__LIGHT_TEXT_RGB__, 0.75);
        --token-color-icon-sidebar: rgba(__LIGHT_TEXT_RGB__, 0.6);
        --token-color-icon-sidebar-selected: var(--token-color-icon-primary);
        --token-color-text-primary: rgba(__LIGHT_TEXT_RGB__, 0.98);
        --token-color-text-secondary: rgba(__LIGHT_TEXT_RGB__, 0.8);
        --token-color-text-disabled: rgba(__LIGHT_TEXT_RGB__, 0.45);
        --token-color-text-sidebar-selected: var(--token-color-text-primary);
        --token-color-text-sidebar: var(--token-color-text-secondary);
        --token-color-text-label-badge: rgba(__LIGHT_TEXT_RGB__, 0.85);
        --token-color-text-chip: rgb(var(--token-rgb-black));
        --token-color-background-base: rgba(234, 235, 238, 0.6);
        --token-color-background-secondary: rgba(245, 245, 245, 0.5);
        --token-color-background-sidebar: var(--token-color-background-base);
        --token-color-background-input-base: rgba(255, 255, 255, 0.7);
        --token-color-background-input-disabled: rgba(245, 245, 245, 0.6);
        --token-color-background-label-badge: rgb(230, 230, 230);
        --token-color-background-card: rgba(255, 255, 255, 0.85);
        --token-color-background-skrim: rgba(0, 0, 0, 0.6);
        --token-color-background-divider: rgba(224, 224, 224, 0.3);
        --token-color-background-scrollbar-thumb: rgb(180, 180, 180);
        --token-color-background-label-badge-red: var(--token-color-feedback-error);
        --token-color-background-label-badge-blue: var(--token-color-feedback-info);
        --token-color-background-label-badge-green: rgb(78, 183, 128);
        --token-color-background-label-badge-yellow: var(--token-color-feedback-warning);
        --token-color-background-label-badge-grey: rgb(83, 90, 103);
        --token-color-background-popup-scrim: rgba(0, 0, 0, 1);
        --token-color-border-card: rgba(255, 255, 255, 0.3);
        --token-color-switch-button-unchecked: rgba(0, 0, 0, 0.6);
        --token-color-switch-track-unchecked: rgba(0, 0, 0, 0.3);
        --token-color-switch-checked-button: rgb(__LIGHT_PRIMARY_RGB__);
        --token-color-codemirror-string: rgb(0, 77, 153);
        --token-color-codemirror-keyword: rgb(70, 112, 216);
        --token-color-codemirror-number: rgb(204, 85, 0);
        --token-shadow-card-medium: 0 12px 20px rgba(0, 0, 0, 0.15);
        --token-size-radius-small: 10px;
        --token-size-radius-medium: 14px;
        --token-size-radius-large: 18px;
        --token-size-radius-card: var(--token-size-radius-large);
        --token-size-width-border-card: 0.5px;
        --token-size-height-slider: 5px;
        --token-size-height-navbar: 60px;
        --token-size-font-xs: calc(10px * var(--ha-font-size-scale));
        --token-size-font-s: calc(12px * var(--ha-font-size-scale));
        --token-size-font-m: calc(14px * var(--ha-font-size-scale));
        --token-size-font-l: calc(15px * var(--ha-font-size-scale));
        --token-size-font-xl: calc(20px * var(--ha-font-size-scale));
        --token-size-font-2xl: calc(25px * var(--ha-font-size-scale));
        --token-size-font-3xl: calc(29px * var(--ha-font-size-scale));
        --token-size-font-4xl: calc(33px * var(--ha-font-size-scale));
        --token-size-font-5xl: calc(42px * var(--ha-font-size-scale));
        --token-size-spacing-medium: 17px;
        --token-size-section-min-width: 320px;
        --token-color-transparent: rgba(0, 0, 0, 0);
        --token-color-black: rgb(0, 0, 0);
        --token-color-white: rgb(255, 255, 255);
        --token-opacity-ripple-hover: 0.1;
        --token-font-family-primary: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        --token-weight-font-title-card: 500;
        
        # Additional color variables
        --token-color-red: rgb(var(--token-rgb-red));
        --token-color-green: rgb(var(--token-rgb-green));
        --token-color-blue: rgb(var(--token-rgb-blue));
        --token-color-yellow: rgb(var(--token-rgb-yellow));
        --token-color-orange: rgb(var(--token-rgb-orange));
        --token-color-purple: rgb(var(--token-rgb-purple));
        --token-color-pink: rgb(var(--token-rgb-pink));
        --token-color-amber: rgb(var(--token-rgb-amber));
        --token-color-cyan: rgb(var(--token-rgb-cyan));
        --token-color-teal: rgb(var(--token-rgb-teal));
        --token-color-lime: rgb(var(--token-rgb-lime));
        --token-color-light-green: rgb(var(--token-rgb-light-green));
        --token-color-deep-orange: rgb(var(--token-rgb-deep-orange));
        --token-color-brown: rgb(var(--token-rgb-brown));
        --token-color-grey: rgb(var(--token-rgb-grey));
        --token-color-blue-grey: rgb(var(--token-rgb-blue-grey));
        --token-color-indigo: rgb(var(--token-rgb-indigo));
        --token-color-deep-purple: rgb(var(--token-rgb-deep-purple));
        --token-color-light-blue: rgb(var(--token-rgb-light-blue));
       }

       /* Custom text divider row size fix */
       custom-text-divider-row .text-divider-content {
        background: #fff !important; /* or your color */
        opacity: 1 !important;
        box-shadow: none !important;
        border-radius: 10px !important; /* adjust as needed */
        padding: 0 8px !important;
        --text-divider-font-size: 16px !important;
        --text-divider-line-size: 1px;
        --text-divider-color: rgba(__LIGHT_TEXT_RGB__, 1) !important;
       }

      # =========================
      # TYPOGRAPHY
      # =========================
      ha-font-family-body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      ha-font-family-heading: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      ha-font-family-code: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      ha-font-family-longform: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      ha-card-header-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      mdc-typography-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      mdc-typography-button-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      mdc-typography-body1-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      md-list-item-label-text-font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-common-base_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-common-code_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-body1_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-subhead_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-headline_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-caption_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
      paper-font-title_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'

      ha-font-weight-normal: '400'
      ha-font-weight-medium: '500'
      ha-font-weight-bold: '700'
      ha-font-weight-body: '400'
      ha-font-weight-heading: '500'
      ha-font-weight-action: '500'
      mdc-typography-button-font-weight: '500'
      title-font-weight: 'var(--token-weight-font-title-card)'

      ha-font-size-xs: '10px'
      ha-font-size-s: '12px'
      ha-font-size-m: '14px'
      ha-font-size-l: '15px'
      ha-font-size-xl: '20px'
      ha-font-size-2xl: '25px'
      ha-font-size-3xl: '29px'
      ha-font-size-4xl: '33px'
      ha-font-size-5xl: '42px'
      title-font-size: '20px'
      ha-heading-card-title-font-size: 'var(--token-size-font-l)'
      ha-heading-card-title-font-weight: '500'
      ha-font-smoothing: 'antialiased'

      # =========================
      # COLORS & MISCELLANEOUS
      # =========================
      
      # 1.2.1 - change add HA 2025.8 primary color scale aligned to theme
      # We REMOVE the hardcoded list to allow HA to generate shades from primary-color
      # ha-color-primary-05 ... 95 are removed so they inherit from primary-color correctly
      
      primary-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.98)'
      secondary-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.8)'
      text-primary-color: 'rgba(__LIGHT_TEXT_RGB__, 0.98)'
      disabled-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.45)'
      text-light-primary-color: 'rgb(28, 29, 33)'
      paper-item-icon-color: 'rgba(__LIGHT_TEXT_RGB__, 0.95)'
      state-inactive-color: 'rgba(__LIGHT_TEXT_RGB__, 0.8)'
      state-icon-color: 'rgba(__LIGHT_TEXT_RGB__, 0.95)'
      state-on-color: 'rgb(118, 214, 152)'
      state-off-color: 'rgb(234, 114, 135)'
      label-badge-text-color: 'rgba(__LIGHT_TEXT_RGB__, 0.85)'
      label-badge-red: 'rgb(234, 114, 135)'
      label-badge-blue: 'rgb(106, 116, 211)'
      label-badge-green: 'rgb(78, 183, 128)'
      label-badge-yellow: 'rgb(255, 219, 117)'
      label-badge-grey: 'rgb(83, 90, 103)'
      ha-chip-text-color: 'rgb(0, 0, 0)'

      primary-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      dark-primary-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      light-primary-color: 'rgb(167, 182, 199)'
      accent-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      divider-color: 'rgba(224, 224, 224, 0.3)'
      scrollbar-thumb-color: 'rgb(180, 180, 180)'
      disabled-color: 'rgb(173, 176, 184)'
      info-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      success-color: 'rgb(118, 214, 152)'
      warning-color: 'rgb(255, 219, 117)'
      error-color: 'rgb(234, 114, 135)'
      background-image: "center / cover no-repeat fixed url('__LIGHT_BG__')"
      lovelace-background: var(--background-image)
      primary-background-color: 'rgba(254, 244, 242, 1)'
      secondary-background-color: 'rgba(245, 245, 245, 0.5)'
      clear-background-color: 'rgba(254, 244, 242, 0.9)'
      card-background-color: 'rgba(254, 244, 242, 0.9)'
      ha-card-background: 'rgba(254, 244, 242, 0.9)'
      ha-card-border-radius: '18px'
      ha-card-border-color: 'rgba(255, 255, 255, 0.3)'
      ha-card-border-width: '0.5px'
      ha-card-border-style: 'solid'
      ha-card-border: '0.5px solid rgba(255, 255, 255, 0.3)'
      ha-card-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.15)'
      ha-view-sections-column-gap: '17px'
      ha-view-sections-column-min-width: 320px
      navbar-background-color: 'transparent !important'

      # Sliders, toggles, switches
      paper-slider-knob-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-slider-knob-start-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-slider-pin-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-slider-active-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-slider-secondary-color: 'rgb(167, 182, 199)'
      switch-checked-button-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      switch-checked-track-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      switch-unchecked-button-color: 'rgba(0, 0, 0, 0.6)'
      switch-unchecked-track-color: 'rgba(0, 0, 0, 0.3)'
      paper-toggle-button-checked-button-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-toggle-button-checked-bar-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      paper-toggle-button-unchecked-button-color: 'rgba(0, 0, 0, 0.6)'
      paper-toggle-button-unchecked-bar-color: 'rgba(0, 0, 0, 0.3)'
      mdc-checkbox-unchecked-color: 'rgba(19, 21, 54, 0.75)'
      mdc-radio-unchecked-color: 'rgba(19, 21, 54, 0.75)'
      mdc-ripple-hover-opacity: '0.1'

      # Inputs
      input-background-color: 'rgba(254, 255, 252, 0.8)'
      input-background-token-color-disabled: 'rgba(254, 255, 252, 0.8)'
      input-fill-color: 'rgba(255, 255, 252, 0.8)'
      input-ink-color: 'rgba(19, 21, 54, 0.98)'
      input-label-ink-color: 'rgba(19, 21, 54, 0.98)'
      input-disabled-fill-color: 'rgba(245, 245, 245, 0.6)'
      input-disabled-ink-color: 'rgba(19, 21, 54, 0.45)'
      input-disabled-label-ink-color: 'rgba(19, 21, 54, 0.45)'
      input-idle-line-color: 'transparent'
      input-dropdown-icon-color: 'rgba(19, 21, 54, 0.8)'
      input-hover-line-color: 'rgb(__LIGHT_PRIMARY_RGB__)'
      mdc-select-idle-line-color: 'transparent'
      mdc-text-field-idle-line-color: 'transparent'

      # Code Editor & Misc
      code-editor-background-color: 'rgba(234, 235, 238, 1)'
      codemirror-meta: 'rgba(19, 21, 54, 0.98)'
      codemirror-property: 'rgb(__LIGHT_PRIMARY_RGB__)'
      codemirror-atom: 'rgb(__LIGHT_PRIMARY_RGB__)'
      codemirror-string: 'rgb(0, 77, 153)'
      codemirror-keyword: 'rgb(70, 112, 216)'
      codemirror-number: 'rgb(204, 85, 0)'
      mcg-title-font-weight: '400'
      mush-title-font-weight: '500'
      mush-title-font-size: 'var(--token-size-font-2xl)'
      light-grey-color: 'rgb(103, 104, 119)'
      mush-rgb-grey: '103, 104, 119)'

      # Misc sizes
      paper-slider-height: '5px'
      border-radius: '18px'

    dark:
      card-mod-theme: 'Frosted Glass Custom'

      # =========================
      # DARK MODE COLORS
      # =========================
      primary-color: 'rgb(__DARK_PRIMARY_RGB__)'
      accent-color: 'rgb(__DARK_PRIMARY_RGB__)'
      
      # Text Colors
      primary-text-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      secondary-text-color: 'rgba(__DARK_TEXT_RGB__, 0.8)'
      text-primary-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      
      # Removed hardcoded primary scale so it auto-generates
      
      # Background
      background-image: "center / cover no-repeat fixed url('__DARK_BG__')"
      lovelace-background: var(--background-image)

      # --- Tokens ---
      card-mod-root: |
        :host {
          --token-rgb-primary: __DARK_PRIMARY_RGB__;
          --token-color-primary: rgb(__DARK_PRIMARY_RGB__);
          --token-rgb-cyan: __DARK_PRIMARY_RGB__;
          --token-rgb-teal: __DARK_PRIMARY_RGB__;
          --token-color-feedback-info: rgb(__DARK_PRIMARY_RGB__);
          --token-color-switch-checked-button: rgb(__DARK_PRIMARY_RGB__);
          
          /* Dynamic Text Colors */
          --token-color-text-primary: rgba(__DARK_TEXT_RGB__, 0.98);
          --token-color-text-secondary: rgba(__DARK_TEXT_RGB__, 0.8);
          --token-color-icon-primary: rgba(__DARK_TEXT_RGB__, 0.95);
          --token-color-icon-secondary: rgba(__DARK_TEXT_RGB__, 0.75);
          
          /* Base variables */
          --ha-card-background: rgba(30, 30, 30, 0.1);
          --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.28);
          --ha-card-border-width: 0.5px;
          --ha-card-border-color: rgba(234, 235, 238, 0.1);
          --ha-card-backdrop-filter: blur(10px) saturate(1.2);
          
          /* Glass system tokens */
          --ha-card-glass-tint: rgba(28, 29, 33, 0.18);
          --ha-card-glass-inset-shadow: 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.15) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.1) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18);

          /* Tokens - match structure to Light theme for consistency */
          --token-rgb-black: 0, 0, 0;
          --token-rgb-white: 234, 235, 238;
          --token-rgb-purple: 129, 45, 250;
          --token-rgb-pink: 204, 0, 136;
          --token-rgb-red: 204, 0, 51;
          --token-rgb-deep-purple: 98, 0, 234;
          --token-rgb-indigo: 48, 63, 159;
          --token-rgb-blue: 33, 150, 243;
          --token-rgb-light-blue: 3, 169, 244;
          --token-rgb-green: 56, 142, 60;
          --token-rgb-light-green: 139, 195, 74;
          --token-rgb-lime: 205, 220, 57;
          --token-rgb-yellow: 250, 183, 0;
          --token-rgb-amber: 255, 193, 7;
          --token-rgb-orange: 255, 158, 0;
          --token-rgb-deep-orange: 255, 87, 34;
          --token-rgb-brown: 121, 85, 72;
          --token-rgb-grey: 103, 104, 119;
          --token-rgb-blue-grey: 96, 125, 139;
          --token-rgb-disabled: 189, 189, 189;
          --token-rgb-state-inactive: 176, 190, 197;
          
          --token-color-primary-light: rgb(167 182 199);
          --token-color-accent: rgb(var(--token-rgb-teal));
          --token-color-disabled: rgb(173 176 184);
          --token-color-feedback-warning: rgb(255, 219, 117);
          --token-color-feedback-error: rgb(234, 114, 135);
          --token-color-feedback-success: rgb(118, 214, 152);
          --token-color-icon-sidebar: rgba(234, 235, 238, 0.6);
          --token-color-icon-sidebar-selected: var(--token-color-icon-primary);
          --token-color-text-disabled: rgba(234, 235, 238, 0.45);
          --token-color-text-sidebar-selected: var(--token-color-text-primary);
          --token-color-text-sidebar: var(--token-color-text-secondary);
          --token-color-text-label-badge: rgba(234, 235, 238, 0.85);
          --token-color-text-chip: rgb(var(--token-rgb-white));
          --token-color-background-base: rgba(25, 28, 45, 0.8);
          --token-color-background-secondary: rgba(30, 33, 54, 0.7);
          --token-color-background-sidebar: var(--token-color-background-base);
          --token-color-background-input-base: rgba(30, 33, 54, 0.7);
          --token-color-background-input-disabled: rgba(30, 33, 54, 0.5);
          --token-color-background-label-badge: rgb(60, 60, 78);
          --token-color-background-card: rgba(28, 29, 33, 0.85);
          --token-color-background-skrim: rgba(0, 0, 0, 0.7);
          --token-color-background-divider: rgba(84, 84, 98, 0.28);
          --token-color-background-scrollbar-thumb: rgb(68, 68, 88);
          --token-color-background-label-badge-red: var(--token-color-feedback-error);
          --token-color-background-label-badge-blue: var(--token-color-feedback-info);
          --token-color-background-label-badge-green: rgb(78, 183, 128);
          --token-color-background-label-badge-yellow: var(--token-color-feedback-warning);
          --token-color-background-label-badge-grey: rgb(83, 90, 103);
          --token-color-background-popup-scrim: rgba(0, 0, 0, 1);
          --token-color-border-card: rgba(234, 235, 238, 0.22);
          --token-color-switch-button-unchecked: rgba(234, 235, 238, 0.3);
          --token-color-switch-track-unchecked: rgba(234, 235, 238, 0.18);
          --token-color-codemirror-string: rgb(164, 209, 255);
          --token-color-codemirror-keyword: rgb(148, 182, 255);
          --token-color-codemirror-number: rgb(255, 171, 64);
          --token-shadow-card-medium: 0 12px 20px rgba(0, 0, 0, 0.28);
          --token-size-radius-small: 10px;
          --token-size-radius-medium: 14px;
          --token-size-radius-large: 18px;
          --token-size-radius-card: var(--token-size-radius-large);
          --token-size-width-border-card: 0.5px;
          --token-size-height-slider: 5px;
          --token-size-height-navbar: 60px;
          --token-size-font-xs: calc(10px * var(--ha-font-size-scale));
          --token-size-font-s: calc(12px * var(--ha-font-size-scale));
          --token-size-font-m: calc(14px * var(--ha-font-size-scale));
          --token-size-font-l: calc(15px * var(--ha-font-size-scale));
          --token-size-font-xl: calc(20px * var(--ha-font-size-scale));
          --token-size-font-2xl: calc(25px * var(--ha-font-size-scale));
          --token-size-font-3xl: calc(29px * var(--ha-font-size-scale));
          --token-size-font-4xl: calc(33px * var(--ha-font-size-scale));
          --token-size-font-5xl: calc(42px * var(--ha-font-size-scale));
          --token-size-spacing-medium: 17px;
          --token-size-section-min-width: 320px;
          --token-color-transparent: rgba(0, 0, 0, 0);
          --token-color-black: rgb(0, 0, 0);
          --token-color-white: rgb(234, 235, 238);
          --token-opacity-ripple-hover: 0.1;
          --token-font-family-primary: -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
          --token-weight-font-title-card: 500;
          
          # Additional color variables
          --token-color-red: rgb(var(--token-rgb-red));
          --token-color-green: rgb(var(--token-rgb-green));
          --token-color-blue: rgb(var(--token-rgb-blue));
          --token-color-yellow: rgb(var(--token-rgb-yellow));
          --token-color-orange: rgb(var(--token-rgb-orange));
          --token-color-purple: rgb(var(--token-rgb-purple));
          --token-color-pink: rgb(var(--token-rgb-pink));
          --token-color-amber: rgb(var(--token-rgb-amber));
          --token-color-cyan: rgb(var(--token-rgb-cyan));
          --token-color-teal: rgb(var(--token-rgb-teal));
          --token-color-lime: rgb(var(--token-rgb-lime));
          --token-color-light-green: rgb(var(--token-rgb-light-green));
          --token-color-deep-orange: rgb(var(--token-rgb-deep-orange));
          --token-color-brown: rgb(var(--token-rgb-brown));
          --token-color-grey: rgb(var(--token-rgb-grey));
          --token-color-blue-grey: rgb(var(--token-rgb-blue-grey));
          --token-color-indigo: rgb(var(--token-rgb-indigo));
          --token-color-deep-purple: rgb(var(--token-rgb-deep-purple));
          --token-color-light-blue: rgb(var(--token-rgb-light-blue));
        }

        custom-text-divider-row .text-divider-content {
          background: #181929 !important; opacity: 1 !important; box-shadow: none !important; border-radius: 10px !important; padding: 0 8px !important;
          --text-divider-font-size: 16px !important; --text-divider-line-size: 1px; 
          --text-divider-color: rgba(__DARK_TEXT_RGB__, 1) !important;
        }

      # --- Rest of Dark Colors ---
      app-header-backdrop-filter: 'blur(8px) saturate(1.1)'
      app-header-background-color: 'rgba(30, 30, 30, 0.01)'
      app-header-text-color: 'rgba(__DARK_TEXT_RGB__, 0.95)'
      app-header-edit-background-color: 'rgba(30, 33, 54, 0.8)'
      app-header-edit-text-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      app-theme-color: 'rgb(0, 0, 0)'
      sidebar-background-color: 'rgba(30, 30, 30, 0.8)'
      sidebar-icon-color: 'rgba(__DARK_TEXT_RGB__, 0.6)'
      sidebar-text-color: 'rgba(__DARK_TEXT_RGB__, 0.8)'
      sidebar-selected-icon-color: 'rgba(__DARK_TEXT_RGB__, 0.95)'
      sidebar-selected-text-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      ha-dialog-surface-backdrop-filter: 'blur(8px)'
      ha-dialog-surface-background: 'rgba(30, 30, 30, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.25)'
      paper-dialog-background-color: 'rgba(30, 30, 30, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.8)'
      
      disabled-text-color: 'rgba(__DARK_TEXT_RGB__, 0.45)'
      text-light-primary-color: 'rgb(234, 235, 238)'
      paper-item-icon-color: 'rgba(__DARK_TEXT_RGB__, 0.95)'
      state-inactive-color: 'rgba(__DARK_TEXT_RGB__, 0.8)'
      state-icon-color: 'rgba(__DARK_TEXT_RGB__, 0.95)'
      state-on-color: 'rgb(118, 214, 152)'
      state-off-color: 'rgb(234, 114, 135)'
      label-badge-text-color: 'rgba(__DARK_TEXT_RGB__, 0.85)'
      label-badge-red: 'rgb(234, 114, 135)'
      label-badge-blue: 'rgb(106, 116, 211)'
      label-badge-green: 'rgb(78, 183, 128)'
      label-badge-yellow: 'rgb(255, 219, 117)'
      label-badge-grey: 'rgb(83, 90, 103)'
      ha-chip-text-color: 'rgb(234, 235, 238)'
      dark-primary-color: 'rgb(106, 116, 211)'
      light-primary-color: 'rgb(167, 182, 199)'
      divider-color: 'rgba(84, 84, 98, 0.28)'
      scrollbar-thumb-color: 'rgb(68, 68, 88)'
      disabled-color: 'rgb(173, 176, 184)'
      info-color: 'rgb(__DARK_PRIMARY_RGB__)'
      success-color: 'rgb(118, 214, 152)'
      warning-color: 'rgb(255, 219, 117)'
      error-color: 'rgb(234, 114, 135)'
      
      primary-background-color: 'rgba(30, 30, 30, 1)'
      secondary-background-color: 'rgba(30, 33, 54, 0.6)'
      clear-background-color: 'rgba(30, 33, 54, 0.7)'
      card-background-color: 'rgba(30, 30, 30, 0.85)'
      ha-card-background: 'rgba(30, 30, 30, 0.9)'
      ha-card-border-radius: '18px'
      ha-card-border-color: 'rgba(234, 235, 238, 0.22)'
      ha-card-border-width: '0.5px'
      ha-card-border-style: 'solid'
      ha-card-border: '0.5px solid rgba(234, 235, 238, 0.1)'
      ha-card-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.28)'
      ha-view-sections-column-gap: '17px'
      ha-view-sections-column-min-width: 320px
      
      paper-slider-knob-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-slider-knob-start-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-slider-pin-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-slider-active-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-slider-secondary-color: 'rgb(167, 182, 199)'
      switch-checked-button-color: 'rgb(__DARK_PRIMARY_RGB__)'
      switch-checked-track-color: 'rgb(__DARK_PRIMARY_RGB__)'
      switch-unchecked-button-color: 'rgba(234, 235, 238, 0.3)'
      switch-unchecked-track-color: 'rgba(234, 235, 238, 0.18)'
      paper-toggle-button-checked-button-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-toggle-button-checked-bar-color: 'rgb(__DARK_PRIMARY_RGB__)'
      paper-toggle-button-unchecked-button-color: 'rgba(234, 235, 238, 0.3)'
      paper-toggle-button-unchecked-bar-color: 'rgba(234, 235, 238, 0.18)'
      mdc-checkbox-unchecked-color: 'rgba(__DARK_TEXT_RGB__, 0.75)'
      mdc-radio-unchecked-color: 'rgba(__DARK_TEXT_RGB__, 0.75)'
      mdc-ripple-hover-opacity: '0.1'
      control-button-background-color: 'rgba(173, 176, 184, 0.2)'
      
      input-background-color: 'rgba(50, 50, 50, 0.1)'
      input-background-token-color-disabled: 'rgba(50, 50, 50, 0.1)'
      input-fill-color: 'rgba(50,50, 50, 0.1)'
      input-ink-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      input-label-ink-color: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      input-disabled-fill-color: 'rgba(30, 33, 54, 0.5)'
      input-disabled-ink-color: 'rgba(__DARK_TEXT_RGB__, 0.45)'
      input-disabled-label-ink-color: 'rgba(__DARK_TEXT_RGB__, 0.45)'
      input-idle-line-color: 'transparent'
      input-dropdown-icon-color: 'rgba(__DARK_TEXT_RGB__, 0.8)'
      input-hover-line-color: 'rgb(__DARK_PRIMARY_RGB__)'
      mdc-select-idle-line-color: 'transparent'
      mdc-text-field-idle-line-color: 'transparent'
      code-editor-background-color: 'rgba(25, 28, 45, 1)'
      codemirror-meta: 'rgba(__DARK_TEXT_RGB__, 0.98)'
      codemirror-property: 'rgb(__DARK_PRIMARY_RGB__)'
      codemirror-atom: 'rgb(__DARK_PRIMARY_RGB__)'
      codemirror-string: 'rgb(164, 209, 255)'
      codemirror-keyword: 'rgb(148, 182, 255)'
      codemirror-number: 'rgb(255, 171, 64)'
      mcg-title-font-weight: '400'
      mush-title-font-weight: '500'
      mush-title-font-size: 'var(--token-size-font-2xl)'
      light-grey-color: 'rgb(103, 104, 119)'
      mush-rgb-grey: '103, 104, 119'
      paper-slider-height: '5px'
      border-radius: '18px'
      
      # --- CARD STYLING (Restored Glass Effect) ---
      card-mod-card: |
        ha-card { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }
        
        /* THE IMPORTANT GLASS LAYER */
        ha-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--ha-card-glass-tint, rgba(28, 29, 33, 0.18));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          z-index: -1; pointer-events: none; border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow, 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.15) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.1) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18));
        }
        
        /* Exclusions */
        :host(hui-heading-card) ha-card, :host(hui-glance-card) ha-card { background: none !important; backdrop-filter: none !important; }
        :host(hui-heading-card) ha-card::before, :host(hui-glance-card) ha-card::before { content: none !important; }
        .mdc-data-table { background: none !important; }
        .mdc-data-table__header-cell { background: rgba(30, 33, 54, 0.18) !important; backdrop-filter: var(--ha-card-backdrop-filter) !important; box-shadow: var(--ha-card-glass-inset-shadow) !important; }
        :host(.text-only) ha-card, :host(.text-only) ha-card::before, ha-card.text-only, ha-card.text-only::before { background: none !important; backdrop-filter: none !important; box-shadow: none !important; content: none !important; }
        :host(mushroom-title-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-title-card) ha-card::before { content: none !important; }
        :host(.type-custom-bubble-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; border-radius: 0px !important; }
        :host(.type-custom-bubble-card) ha-card::before { content: none !important; background: none !important; }
        :host(mushroom-chips-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-chips-card) ha-card::before { content: none !important; background: none !important; }
        
        /* Navbar Fix */
        navbar-card { --navbar-background-color: transparent !important; }
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }

  # =========================
  # TYPOGRAPHY
  # =========================
  ha-font-family-body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-heading: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-code: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-longform: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-card-header-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-button-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-body1-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  md-list-item-label-text-font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-common-base_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-common-code_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-body1_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-subhead_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-headline_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-caption_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-title_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'

  ha-font-weight-normal: '400'
  ha-font-weight-medium: '500'
  ha-font-weight-bold: '700'
  ha-font-weight-body: '400'
  ha-font-weight-heading: '500'
  ha-font-weight-action: '500'
  mdc-typography-button-font-weight: '500'
  title-font-weight: 'var(--token-weight-font-title-card)'

  ha-font-size-xs: '10px'
  ha-font-size-s: '12px'
  ha-font-size-m: '14px'
  ha-font-size-l: '15px'
  ha-font-size-xl: '20px'
  ha-font-size-2xl: '25px'
  ha-font-size-3xl: '29px'
  ha-font-size-4xl: '33px'
  ha-font-size-5xl: '42px'
  title-font-size: '20px'
  ha-heading-card-title-font-size: 'var(--token-size-font-l)'
  ha-heading-card-title-font-weight: '500'
  ha-font-smoothing: 'antialiased'

  # --- End of Theme ---
"""
