"""Constants for the Frosted Glass Manager integration."""

DOMAIN = "frosted_glass_manager"

# Default values (Fialová pre obe)
DEFAULT_LIGHT_RGB = [106, 116, 211]
DEFAULT_DARK_RGB = [106, 116, 211]

THEME_FILENAME = "frosted_glass_custom.yaml"

# Python replace holders:
# __LIGHT_RGB_STR__  -> "106, 116, 211"
# __LIGHT_HEX__      -> "#6A74D3"
# __DARK_RGB_STR__   -> "106, 116, 211"
# __DARK_HEX__       -> "#6A74D3"

THEME_TEMPLATE = """
# Frosted Glass Custom
# Auto-generated by Frosted Glass Manager based on v1.2.2

Frosted Glass Custom:
  card-mod-theme: "Frosted Glass Custom"

  modes:
    light:
      # =========================
      # LIGHT MODE COLORS
      # =========================
      primary-color: 'rgb(__LIGHT_RGB_STR__)'
      accent-color: 'rgb(__LIGHT_RGB_STR__)'
      
      # Hex variations for HA palette
      ha-color-primary-50: '__LIGHT_HEX__'
      color-primary-50: '__LIGHT_HEX__'
      
      # Tokeny
      card-mod-root: |
        :host {
          --token-rgb-primary: __LIGHT_RGB_STR__;
          --token-color-primary: rgb(__LIGHT_RGB_STR__);
          --token-rgb-cyan: __LIGHT_RGB_STR__;
          --token-rgb-teal: __LIGHT_RGB_STR__;
          --token-color-feedback-info: rgb(__LIGHT_RGB_STR__);
          
          /* Sliders & Switch overrides */
          --token-color-switch-checked-button: rgb(__LIGHT_RGB_STR__);
          
          /* Base theme variables */
          --ha-card-background: rgba(242, 245, 255, 0.1);
          --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.15);
          --ha-card-border-width: 0.5px;
          --ha-card-border-color: rgba(255, 255, 255, 0.3);
          --ha-card-backdrop-filter: blur(8px) saturate(1.2);
          
          /* Glass system tokens */
          --ha-card-glass-tint: rgba(255, 255, 255, 0.08);
          --ha-card-glass-inset-shadow: 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset, 0 0 8px 1px rgba(255, 255, 255, 0.10) inset, 0 0 2px 0 rgba(0, 0, 0, 0.10);
        }
        
      # --- Rest of Light Mode Settings ---
      app-header-backdrop-filter: 'blur(6px) saturate(1.2)'
      app-header-background-color: 'rgba(234, 235, 238, 0.1)'
      app-header-text-color: 'rgba(19, 21, 54, 0.95)'
      app-header-edit-background-color: 'rgba(255, 255, 255, 0.8)'
      app-header-edit-text-color: 'rgba(19, 21, 54, 0.98)'
      app-theme-color: 'rgb(91, 138, 168)'
      sidebar-background-color: 'rgba(254, 244, 242, 0.7)'
      sidebar-icon-color: 'rgba(19, 21, 54, 0.6)'
      sidebar-text-color: 'rgba(19, 21, 54, 0.8)'
      sidebar-selected-icon-color: 'rgba(19, 21, 54, 0.95)'
      sidebar-selected-text-color: 'rgba(19, 21, 54, 0.98)'
      ha-dialog-surface-backdrop-filter: 'blur(8px)'
      ha-dialog-surface-background: 'rgba(234, 235, 238, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.15)'
      paper-dialog-background-color: 'rgba(234, 235, 238, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.6)'
      
      # Inputs & Elements
      primary-text-color: 'rgba(19, 21, 54, 0.98)'
      secondary-text-color: 'rgba(19, 21, 54, 0.8)'
      text-primary-color: 'rgba(19, 21, 54, 0.98)'
      disabled-text-color: 'rgba(19, 21, 54, 0.45)'
      text-light-primary-color: 'rgb(28, 29, 33)'
      divider-color: 'rgba(224, 224, 224, 0.3)'
      paper-toggle-button-checked-button-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-toggle-button-checked-bar-color: 'rgb(__LIGHT_RGB_STR__)'
      switch-checked-button-color: 'rgb(__LIGHT_RGB_STR__)'
      switch-checked-track-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-knob-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-active-color: 'rgb(__LIGHT_RGB_STR__)'
      input-hover-line-color: 'rgb(__LIGHT_RGB_STR__)'

      background-image: "center / cover no-repeat fixed url('https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-light-background.jpg')"
      lovelace-background: var(--background-image)
      
      # Card Mod Injections
      card-mod-card: |
        ha-card { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }
        ha-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--ha-card-glass-tint, rgba(255, 255, 255, 0.08));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          z-index: -1; pointer-events: none; border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow, 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset, 0 0 8px 1px rgba(255, 255, 255, 0.10) inset, 0 0 2px 0 rgba(0, 0, 0, 0.10));
        }
        :host(hui-heading-card) ha-card, :host(hui-glance-card) ha-card { background: none !important; backdrop-filter: none !important; }
        :host(hui-heading-card) ha-card::before, :host(hui-glance-card) ha-card::before { content: none !important; }
        .mdc-data-table { background: none !important; }
        .mdc-data-table__header-cell { background: rgba(255, 255, 255, 0.1) !important; backdrop-filter: var(--ha-card-backdrop-filter) !important; box-shadow: var(--ha-card-glass-inset-shadow) !important; }
        :host(.text-only) ha-card, :host(.text-only) ha-card::before, ha-card.text-only, ha-card.text-only::before { background: none !important; backdrop-filter: none !important; box-shadow: none !important; content: none !important; }
        :host(mushroom-title-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-title-card) ha-card::before { content: none !important; }
        :host(.type-custom-bubble-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; border-radius: 0px !important; }
        :host(.type-custom-bubble-card) ha-card::before { content: none !important; background: none !important; }
        :host(mushroom-chips-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-chips-card) ha-card::before { content: none !important; background: none !important; }
        navbar-background-color: 'transparent !important'
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }

    dark:
      # =========================
      # DARK MODE COLORS
      # =========================
      primary-color: 'rgb(__DARK_RGB_STR__)'
      accent-color: 'rgb(__DARK_RGB_STR__)'
      
      ha-color-primary-50: '__DARK_HEX__'
      color-primary-50: '__DARK_HEX__'

      # Tokeny
      card-mod-root: |
        :host {
          --token-rgb-primary: __DARK_RGB_STR__;
          --token-color-primary: rgb(__DARK_RGB_STR__);
          --token-rgb-cyan: __DARK_RGB_STR__;
          --token-rgb-teal: __DARK_RGB_STR__;
          --token-color-feedback-info: rgb(__DARK_RGB_STR__);
          
          /* Sliders & Switch overrides */
          --token-color-switch-checked-button: rgb(__DARK_RGB_STR__);
          
          /* Base theme variables */
          --ha-card-background: rgba(30, 30, 30, 0.1);
          --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.28);
          --ha-card-border-width: 0.5px;
          --ha-card-border-color: rgba(234, 235, 238, 0.1);
          --ha-card-backdrop-filter: blur(10px) saturate(1.2);
          
          /* Glass system tokens */
          --ha-card-glass-tint: rgba(28, 29, 33, 0.18);
          --ha-card-glass-inset-shadow: 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.15) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.1) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18);
        }

      # --- Rest of Dark Mode Settings ---
      app-header-backdrop-filter: 'blur(8px) saturate(1.1)'
      app-header-background-color: 'rgba(30, 30, 30, 0.01)'
      app-header-text-color: 'rgba(240, 243, 255, 0.95)'
      app-header-edit-background-color: 'rgba(30, 33, 54, 0.8)'
      app-header-edit-text-color: 'rgba(234, 235, 238, 0.98)'
      app-theme-color: 'rgb(0, 0, 0)'
      sidebar-background-color: 'rgba(30, 30, 30, 0.8)'
      sidebar-icon-color: 'rgba(234, 235, 238, 0.6)'
      sidebar-text-color: 'rgba(234, 235, 238, 0.8)'
      sidebar-selected-icon-color: 'rgba(234, 235, 238, 0.95)'
      sidebar-selected-text-color: 'rgba(234, 235, 238, 0.98)'
      ha-dialog-surface-backdrop-filter: 'blur(8px)'
      ha-dialog-surface-background: 'rgba(30, 30, 30, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.25)'
      paper-dialog-background-color: 'rgba(30, 30, 30, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.8)'
      
      # Inputs & Elements
      primary-text-color: 'rgba(234, 235, 238, 0.98)'
      secondary-text-color: 'rgba(234, 235, 238, 0.8)'
      text-primary-color: 'rgba(234, 235, 238, 0.98)'
      disabled-text-color: 'rgba(234, 235, 238, 0.45)'
      text-light-primary-color: 'rgb(234, 235, 238)'
      divider-color: 'rgba(84, 84, 98, 0.28)'
      paper-toggle-button-checked-button-color: 'rgb(__DARK_RGB_STR__)'
      paper-toggle-button-checked-bar-color: 'rgb(__DARK_RGB_STR__)'
      switch-checked-button-color: 'rgb(__DARK_RGB_STR__)'
      switch-checked-track-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-knob-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-active-color: 'rgb(__DARK_RGB_STR__)'
      input-hover-line-color: 'rgb(__DARK_RGB_STR__)'

      background-image: "center / cover no-repeat fixed url('https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-dark-background.jpg')"
      lovelace-background: var(--background-image)
      
      # Card Mod Injections
      card-mod-card: |
        ha-card { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }
        ha-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--ha-card-glass-tint, rgba(28, 29, 33, 0.18));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          z-index: -1; pointer-events: none; border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow, 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.22) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.18) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18));
        }
        :host(hui-heading-card) ha-card, :host(hui-glance-card) ha-card { background: none !important; backdrop-filter: none !important; }
        :host(hui-heading-card) ha-card::before, :host(hui-glance-card) ha-card::before { content: none !important; }
        .mdc-data-table { background: none !important; }
        .mdc-data-table__header-cell { background: rgba(30, 33, 54, 0.18) !important; backdrop-filter: var(--ha-card-backdrop-filter) !important; box-shadow: var(--ha-card-glass-inset-shadow) !important; }
        :host(.text-only) ha-card, :host(.text-only) ha-card::before, ha-card.text-only, ha-card.text-only::before { background: none !important; backdrop-filter: none !important; box-shadow: none !important; content: none !important; }
        :host(mushroom-title-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-title-card) ha-card::before { content: none !important; }
        :host(.type-custom-bubble-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; border-radius: 0px !important; }
        :host(.type-custom-bubble-card) ha-card::before { content: none !important; background: none !important; }
        :host(mushroom-chips-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-chips-card) ha-card::before { content: none !important; background: none !important; }
        navbar-background-color: 'transparent !important'
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }
"""
