"""Constants for the Frosted Glass Manager integration."""

DOMAIN = "frosted_glass_manager"

# Default values
DEFAULT_LIGHT_RGB = [106, 116, 211]
DEFAULT_DARK_RGB = [106, 116, 211]
DEFAULT_LIGHT_BG = "https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-light-background.jpg"
DEFAULT_DARK_BG = "https://cdn.jsdelivr.net/gh/wessamlauf/homeassistant-frosted-glass-themes@refs/heads/main/themes/frosted-glass-dark-background.jpg"

THEME_FILENAME = "frosted_glass_custom.yaml"

# Tvoja kompletná téma (v1.2.2)
THEME_TEMPLATE = """
# Frosted Glass Custom
# Auto-generated by Frosted Glass Manager based on v1.2.2

Frosted Glass Custom:
  modes:
    light:
      card-mod-theme: "Frosted Glass Custom"

      # =========================
      # LIGHT MODE COLORS & BACKGROUND
      # =========================
      primary-color: 'rgb(__LIGHT_RGB_STR__)'
      accent-color: 'rgb(__LIGHT_RGB_STR__)'
      
      # Background Image (Dynamic)
      background-image: "center / cover no-repeat fixed url('__LIGHT_BG__')"
      lovelace-background: var(--background-image)

      # --- Hex Variations ---
      ha-color-primary-50: '__LIGHT_HEX__'
      color-primary-50: '__LIGHT_HEX__'

      # =========================
      # CARDS / CARD-MOD
      # =========================
      card-mod-card: |
        /* Base reset */
        ha-card {
          background: transparent;
          backdrop-filter: none;
          -webkit-backdrop-filter: none;
        }

        /* Glass layer */
        ha-card::before {                                                                                      /* 1.2 Glass – glass overlay */
          content: '';
          position: absolute;
          inset: 0;
          background: var(--ha-card-glass-tint, rgba(255, 255, 255, 0.08));                                    /* 1.2 Glass – subtle tint */
          backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          z-index: -1;
          pointer-events: none;
          border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow,                                                         /* 1.2 Glass – inner bevel/glow */
            3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset,
            -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset,
            0 0 8px 1px rgba(255, 255, 255, 0.10) inset,
            0 0 2px 0 rgba(0, 0, 0, 0.10)
          );
        }

        /* Headings + Glance (kept as your exclusions) */
        :host(hui-heading-card) ha-card,
        :host(hui-glance-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }
        :host(hui-heading-card) ha-card::before,
        :host(hui-glance-card) ha-card::before {
          content: none !important;
        }

        /* IMPORTANT: Allow normal Markdown cards to be glassy; only exclude text-only variant */
        /* (Fix) Removed global :host(hui-markdown-card) exclusion you had before                     # 1.2 Glass – bugfix
           so standard Markdown gets the glass. The text-only variant remains excluded below. */

        /* Data tables */
        .mdc-data-table {
          background: none !important;
        }
        .mdc-data-table__header-cell {
          background: rgba(255, 255, 255, 0.1) !important;
          backdrop-filter: var(--ha-card-backdrop-filter) !important;
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter) !important;
          box-shadow: var(--ha-card-glass-inset-shadow) !important;                                           /* 1.2 Glass – consistent bevel */
        }

        /* Markdown card with text_only → no background or blur */                        # 1.1.9 Change - text only markdown and mushroom title card no background // Beginning
        :host(.text-only) ha-card,
        :host(.text-only) ha-card::before,
        ha-card.text-only,
        ha-card.text-only::before {                                                                           /* 1.2 Glass – add ha-card.text-only for compatibility */
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          content: none !important;
        }

        /* Mushroom title card (no background or blur) */
        :host(mushroom-title-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;                                                                         /* 1.2 Glass – ensure no bevel */
        }
        :host(mushroom-title-card) ha-card::before {
          content: none !important;
        }

        /* === Prevent frosted glass from applying to bubble cards ===               # 1.2 Change - Bubble cards are no longer applied */
        :host(.type-custom-bubble-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          border-radius: 0px !important;
        }
        :host(.type-custom-bubble-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }

        /* === Prevent frosted glass from applying to mushroom-chips-card outer container ===      # 1.2 Change - Outer mushroom chips no longer applied  */
        :host(mushroom-chips-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
        }
        :host(mushroom-chips-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }
      
      # --- Tokens & Card Mod Root ---
      card-mod-root: |
        :host {
          --token-rgb-primary: __LIGHT_RGB_STR__;
          --token-color-primary: rgb(__LIGHT_RGB_STR__);
          --token-rgb-cyan: __LIGHT_RGB_STR__;
          --token-rgb-teal: __LIGHT_RGB_STR__;
          --token-color-feedback-info: rgb(__LIGHT_RGB_STR__);
          --token-color-switch-checked-button: rgb(__LIGHT_RGB_STR__);
          
          /* Base variables */
          --ha-card-background: rgba(242, 245, 255, 0.1);
          --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.15);
          --ha-card-border-width: 0.5px;
          --ha-card-border-color: rgba(255, 255, 255, 0.3);
          --ha-card-backdrop-filter: blur(8px) saturate(1.2);
          --ha-card-glass-tint: rgba(255, 255, 255, 0.08);
          --ha-card-glass-inset-shadow: 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset, 0 0 8px 1px rgba(255, 255, 255, 0.10) inset, 0 0 2px 0 rgba(0, 0, 0, 0.10);
        }
        /* Custom text divider row size fix */
        custom-text-divider-row .text-divider-content {
         background: #fff !important; opacity: 1 !important; box-shadow: none !important; border-radius: 10px !important; padding: 0 8px !important;
         --text-divider-font-size: 16px !important; --text-divider-line-size: 1px; --text-divider-color: rgba(19, 21, 54, 1) !important;
        }

      # --- Other Light Colors ---
      app-header-backdrop-filter: 'blur(6px) saturate(1.2)'
      app-header-background-color: 'rgba(234, 235, 238, 0.1)'
      app-header-text-color: 'rgba(19, 21, 54, 0.95)'
      app-header-edit-background-color: 'rgba(255, 255, 255, 0.8)'
      app-header-edit-text-color: 'rgba(19, 21, 54, 0.98)'
      app-theme-color: 'rgb(91, 138, 168)'
      sidebar-background-color: 'rgba(254, 244, 242, 0.7)'
      sidebar-icon-color: 'rgba(19, 21, 54, 0.6)'
      sidebar-text-color: 'rgba(19, 21, 54, 0.8)'
      sidebar-selected-icon-color: 'rgba(19, 21, 54, 0.95)'
      sidebar-selected-text-color: 'rgba(19, 21, 54, 0.98)'
      ha-dialog-surface-backdrop-filter: 'blur(8px)'
      ha-dialog-surface-background: 'rgba(234, 235, 238, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.15)'
      paper-dialog-background-color: 'rgba(234, 235, 238, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.6)'
      primary-text-color: 'rgba(19, 21, 54, 0.98)'
      secondary-text-color: 'rgba(19, 21, 54, 0.8)'
      text-primary-color: 'rgba(19, 21, 54, 0.98)'
      disabled-text-color: 'rgba(19, 21, 54, 0.45)'
      text-light-primary-color: 'rgb(28, 29, 33)'
      paper-item-icon-color: 'rgba(19, 21, 54, 0.95)'
      state-inactive-color: 'rgba(19, 21, 54, 0.8)'
      state-icon-color: 'rgba(19, 21, 54, 0.95)'
      state-on-color: 'rgb(118, 214, 152)'
      state-off-color: 'rgb(234, 114, 135)'
      label-badge-text-color: 'rgba(19, 21, 54, 0.85)'
      label-badge-red: 'rgb(234, 114, 135)'
      label-badge-blue: 'rgb(106, 116, 211)'
      label-badge-green: 'rgb(78, 183, 128)'
      label-badge-yellow: 'rgb(255, 219, 117)'
      label-badge-grey: 'rgb(83, 90, 103)'
      ha-chip-text-color: 'rgb(0, 0, 0)'
      dark-primary-color: 'rgb(__LIGHT_RGB_STR__)'
      light-primary-color: 'rgb(167, 182, 199)'
      divider-color: 'rgba(224, 224, 224, 0.3)'
      scrollbar-thumb-color: 'rgb(180, 180, 180)'
      disabled-color: 'rgb(173, 176, 184)'
      info-color: 'rgb(__LIGHT_RGB_STR__)'
      success-color: 'rgb(118, 214, 152)'
      warning-color: 'rgb(255, 219, 117)'
      error-color: 'rgb(234, 114, 135)'
      primary-background-color: 'rgba(254, 244, 242, 1)'
      secondary-background-color: 'rgba(245, 245, 245, 0.5)'
      clear-background-color: 'rgba(254, 244, 242, 0.9)'
      card-background-color: 'rgba(254, 244, 242, 0.9)'
      ha-card-background: 'rgba(254, 244, 242, 0.9)'
      ha-card-border-radius: '18px'
      ha-card-border-color: 'rgba(255, 255, 255, 0.3)'
      ha-card-border-width: '0.5px'
      ha-card-border-style: 'solid'
      ha-card-border: '0.5px solid rgba(255, 255, 255, 0.3)'
      ha-card-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.15)'
      ha-view-sections-column-gap: '17px'
      ha-view-sections-column-min-width: 320px
      paper-slider-knob-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-knob-start-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-pin-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-active-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-slider-secondary-color: 'rgb(167, 182, 199)'
      switch-checked-button-color: 'rgb(__LIGHT_RGB_STR__)'
      switch-checked-track-color: 'rgb(__LIGHT_RGB_STR__)'
      switch-unchecked-button-color: 'rgba(0, 0, 0, 0.6)'
      switch-unchecked-track-color: 'rgba(0, 0, 0, 0.3)'
      paper-toggle-button-checked-button-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-toggle-button-checked-bar-color: 'rgb(__LIGHT_RGB_STR__)'
      paper-toggle-button-unchecked-button-color: 'rgba(0, 0, 0, 0.6)'
      paper-toggle-button-unchecked-bar-color: 'rgba(0, 0, 0, 0.3)'
      mdc-checkbox-unchecked-color: 'rgba(19, 21, 54, 0.75)'
      mdc-radio-unchecked-color: 'rgba(19, 21, 54, 0.75)'
      mdc-ripple-hover-opacity: '0.1'
      input-background-color: 'rgba(254, 255, 252, 0.8)'
      input-background-token-color-disabled: 'rgba(254, 255, 252, 0.8)'
      input-fill-color: 'rgba(255, 255, 252, 0.8)'
      input-ink-color: 'rgba(19, 21, 54, 0.98)'
      input-label-ink-color: 'rgba(19, 21, 54, 0.98)'
      input-disabled-fill-color: 'rgba(245, 245, 245, 0.6)'
      input-disabled-ink-color: 'rgba(19, 21, 54, 0.45)'
      input-disabled-label-ink-color: 'rgba(19, 21, 54, 0.45)'
      input-idle-line-color: 'transparent'
      input-dropdown-icon-color: 'rgba(19, 21, 54, 0.8)'
      input-hover-line-color: 'rgb(__LIGHT_RGB_STR__)'
      mdc-select-idle-line-color: 'transparent'
      mdc-text-field-idle-line-color: 'transparent'
      code-editor-background-color: 'rgba(234, 235, 238, 1)'
      codemirror-meta: 'rgba(19, 21, 54, 0.98)'
      codemirror-property: 'rgb(__LIGHT_RGB_STR__)'
      codemirror-atom: 'rgb(__LIGHT_RGB_STR__)'
      codemirror-string: 'rgb(0, 77, 153)'
      codemirror-keyword: 'rgb(70, 112, 216)'
      codemirror-number: 'rgb(204, 85, 0)'
      mcg-title-font-weight: '400'
      mush-title-font-weight: '500'
      mush-title-font-size: 'var(--token-size-font-2xl)'
      light-grey-color: 'rgb(103, 104, 119)'
      mush-rgb-grey: '103, 104, 119'
      paper-slider-height: '5px'
      border-radius: '18px'
      
      # --- CARD STYLING ---
      card-mod-card: |
        ha-card { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }
        ha-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--ha-card-glass-tint, rgba(255, 255, 255, 0.08));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(8px) saturate(1.2));
          z-index: -1; pointer-events: none; border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow, 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.30) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.30) inset, 0 0 8px 1px rgba(255, 255, 255, 0.10) inset, 0 0 2px 0 rgba(0, 0, 0, 0.10));
        }
        :host(hui-heading-card) ha-card, :host(hui-glance-card) ha-card { background: none !important; backdrop-filter: none !important; }
        :host(hui-heading-card) ha-card::before, :host(hui-glance-card) ha-card::before { content: none !important; }
        .mdc-data-table { background: none !important; }
        .mdc-data-table__header-cell { background: rgba(255, 255, 255, 0.1) !important; backdrop-filter: var(--ha-card-backdrop-filter) !important; box-shadow: var(--ha-card-glass-inset-shadow) !important; }
        :host(.text-only) ha-card, :host(.text-only) ha-card::before, ha-card.text-only, ha-card.text-only::before { background: none !important; backdrop-filter: none !important; box-shadow: none !important; content: none !important; }
        :host(mushroom-title-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-title-card) ha-card::before { content: none !important; }
        :host(.type-custom-bubble-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; border-radius: 0px !important; }
        :host(.type-custom-bubble-card) ha-card::before { content: none !important; background: none !important; }
        :host(mushroom-chips-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-chips-card) ha-card::before { content: none !important; background: none !important; }
        navbar-card { --navbar-background-color: transparent !important; }
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }

    dark:
      card-mod-theme: 'Frosted Glass Custom'

      # =========================
      # DARK MODE COLORS & BACKGROUND
      # =========================
      primary-color: 'rgb(__DARK_RGB_STR__)'
      accent-color: 'rgb(__DARK_RGB_STR__)'
      
      # Background Image (Dynamic)
      background-image: "center / cover no-repeat fixed url('__DARK_BG__')"
      lovelace-background: var(--background-image)
      
      # --- Hex Variations ---
      ha-color-primary-50: '__DARK_HEX__'
      color-primary-50: '__DARK_HEX__'

      # =========================
      # CARDS / CARD-MOD
      # =========================
      card-mod-card: |
        /* Base reset */
        ha-card {
          background: transparent;
          backdrop-filter: none;
          -webkit-backdrop-filter: none;
        }

        /* Glass layer (variable-driven, matches Light) */
        ha-card::before {                                                                   /* 1.2 Glass – glass overlay */
          content: '';
          position: absolute;
          inset: 0;
          background: var(--ha-card-glass-tint, rgba(28, 29, 33, 0.18));                    /* 1.2 Glass – subtle dark tint */
          backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          z-index: -1;
          pointer-events: none;
          border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow,                                     /* 1.2 Glass – inner bevel/glow */
            3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.22) inset,
            -2px -2px 0.5px -2px rgba(255, 255, 255, 0.18) inset,
            0 0 8px 1px rgba(255, 255, 255, 0.06) inset,
            0 0 2px 0 rgba(0, 0, 0, 0.18)
          );
        }

        /* Headings + Glance (kept excluded) */
        :host(hui-heading-card) ha-card,
        :host(hui-glance-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }
        :host(hui-heading-card) ha-card::before,
        :host(hui-glance-card) ha-card::before {
          content: none !important;
        }

        /* IMPORTANT: Allow normal Markdown to be glassy; only exclude text-only */
        /* (Fix) Removed global :host(hui-markdown-card) exclusion so standard Markdown gets glass. */

        /* Data tables */
        .mdc-data-table {
          background: none !important;
        }
        .mdc-data-table__header-cell {
          background: rgba(30, 33, 54, 0.18) !important;
          backdrop-filter: var(--ha-card-backdrop-filter) !important;
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter) !important;
          box-shadow: var(--ha-card-glass-inset-shadow) !important;                         /* 1.2 Glass – consistent bevel */
        }

        /* Markdown card with text_only → no background or blur */                          # 1.1.9 Change - text only markdown and mushroom title card no background // Beginning
        :host(.text-only) ha-card,
        :host(.text-only) ha-card::before,
        ha-card.text-only,
        ha-card.text-only::before {                                                         /* 1.2 Glass – add ha-card.text-only for compatibility */
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          content: none !important;
        }

        /* Mushroom title card (no background or blur) */
        :host(mushroom-title-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;                                                      /* 1.2 Glass – ensure no bevel */
        }
        :host(mushroom-title-card) ha-card::before {
          content: none !important;
        }

        /* === Prevent frosted/glass from applying to bubble cards ===                      # 1.1.9 Change - Bubble cards are no longer applied */
        :host(.type-custom-bubble-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
          border-radius: 0px !important;
        }
        :host(.type-custom-bubble-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }

        /* === Prevent frosted/glass on mushroom-chips-card outer container ===             # 1.1.9 Change - Outer mushroom chips no longer applied */
        :host(mushroom-chips-card) ha-card {
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
          box-shadow: none !important;
        }
        :host(mushroom-chips-card) ha-card::before {
          content: none !important;
          background: none !important;
          backdrop-filter: none !important;
          -webkit-backdrop-filter: none !important;
        }

        /* (Removed) .bubble-button-card-container styling to avoid conflicts               # 1.2 Glass – matches Light exclusions */
      # --- Tokens & Card Mod Root ---
      card-mod-root: |
        :host {
          --token-rgb-primary: __DARK_RGB_STR__;
          --token-color-primary: rgb(__DARK_RGB_STR__);
          --token-rgb-cyan: __DARK_RGB_STR__;
          --token-rgb-teal: __DARK_RGB_STR__;
          --token-color-feedback-info: rgb(__DARK_RGB_STR__);
          --token-color-switch-checked-button: rgb(__DARK_RGB_STR__);
          
          /* Base variables */
          --ha-card-background: rgba(30, 30, 30, 0.1);
          --ha-card-box-shadow: 0 12px 20px rgba(0, 0, 0, 0.28);
          --ha-card-border-width: 0.5px;
          --ha-card-border-color: rgba(234, 235, 238, 0.1);
          --ha-card-backdrop-filter: blur(10px) saturate(1.2);
          --ha-card-glass-tint: rgba(28, 29, 33, 0.18);
          --ha-card-glass-inset-shadow: 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.15) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.1) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18);
        }
        /* Custom text divider row size fix */
        custom-text-divider-row .text-divider-content {
          background: #181929 !important; opacity: 1 !important; box-shadow: none !important; border-radius: 10px !important; padding: 0 8px !important;
          --text-divider-font-size: 16px !important; --text-divider-line-size: 1px; --text-divider-color: rgba(234, 235, 238, 1) !important;
        }
      
      # --- Rest of Dark Colors ---
      app-header-backdrop-filter: 'blur(8px) saturate(1.1)'
      app-header-background-color: 'rgba(30, 30, 30, 0.01)'
      app-header-text-color: 'rgba(240, 243, 255, 0.95)'
      app-header-edit-background-color: 'rgba(30, 33, 54, 0.8)'
      app-header-edit-text-color: 'rgba(234, 235, 238, 0.98)'
      app-theme-color: 'rgb(0, 0, 0)'
      sidebar-background-color: 'rgba(30, 30, 30, 0.8)'
      sidebar-icon-color: 'rgba(234, 235, 238, 0.6)'
      sidebar-text-color: 'rgba(234, 235, 238, 0.8)'
      sidebar-selected-icon-color: 'rgba(234, 235, 238, 0.95)'
      sidebar-selected-text-color: 'rgba(234, 235, 238, 0.98)'
      ha-dialog-surface-backdrop-filter: 'blur(8px)'
      ha-dialog-surface-background: 'rgba(30, 30, 30, 0.7)'
      dialog-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.25)'
      paper-dialog-background-color: 'rgba(30, 30, 30, 0.7)'
      mdc-dialog-scrim-color: 'rgba(0, 0, 0, 0.8)'
      primary-text-color: 'rgba(234, 235, 238, 0.98)'
      secondary-text-color: 'rgba(234, 235, 238, 0.8)'
      text-primary-color: 'rgba(234, 235, 238, 0.98)'
      disabled-text-color: 'rgba(234, 235, 238, 0.45)'
      text-light-primary-color: 'rgb(234, 235, 238)'
      paper-item-icon-color: 'rgba(234, 235, 238, 0.95)'
      state-inactive-color: 'rgba(234, 235, 238, 0.8)'
      state-icon-color: 'rgba(234, 235, 238, 0.95)'
      state-on-color: 'rgb(118, 214, 152)'
      state-off-color: 'rgb(234, 114, 135)'
      label-badge-text-color: 'rgba(234, 235, 238, 0.85)'
      label-badge-red: 'rgb(234, 114, 135)'
      label-badge-blue: 'rgb(106, 116, 211)'
      label-badge-green: 'rgb(78, 183, 128)'
      label-badge-yellow: 'rgb(255, 219, 117)'
      label-badge-grey: 'rgb(83, 90, 103)'
      ha-chip-text-color: 'rgb(234, 235, 238)'
      dark-primary-color: 'rgb(106, 116, 211)'
      light-primary-color: 'rgb(167, 182, 199)'
      divider-color: 'rgba(84, 84, 98, 0.28)'
      scrollbar-thumb-color: 'rgb(68, 68, 88)'
      disabled-color: 'rgb(173, 176, 184)'
      info-color: 'rgb(__DARK_RGB_STR__)'
      success-color: 'rgb(118, 214, 152)'
      warning-color: 'rgb(255, 219, 117)'
      error-color: 'rgb(234, 114, 135)'
      primary-background-color: 'rgba(30, 30, 30, 1)'
      secondary-background-color: 'rgba(30, 33, 54, 0.6)'
      clear-background-color: 'rgba(30, 33, 54, 0.7)'
      card-background-color: 'rgba(30, 30, 30, 0.85)'
      ha-card-background: 'rgba(30, 30, 30, 0.9)'
      ha-card-border-radius: '18px'
      ha-card-border-color: 'rgba(234, 235, 238, 0.22)'
      ha-card-border-width: '0.5px'
      ha-card-border-style: 'solid'
      ha-card-border: '0.5px solid rgba(234, 235, 238, 0.1)'
      ha-card-box-shadow: '0 12px 20px rgba(0, 0, 0, 0.28)'
      ha-view-sections-column-gap: '17px'
      ha-view-sections-column-min-width: 320px
      paper-slider-knob-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-knob-start-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-pin-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-active-color: 'rgb(__DARK_RGB_STR__)'
      paper-slider-secondary-color: 'rgb(167, 182, 199)'
      switch-checked-button-color: 'rgb(__DARK_RGB_STR__)'
      switch-checked-track-color: 'rgb(__DARK_RGB_STR__)'
      switch-unchecked-button-color: 'rgba(234, 235, 238, 0.3)'
      switch-unchecked-track-color: 'rgba(234, 235, 238, 0.18)'
      paper-toggle-button-checked-button-color: 'rgb(__DARK_RGB_STR__)'
      paper-toggle-button-checked-bar-color: 'rgb(__DARK_RGB_STR__)'
      paper-toggle-button-unchecked-button-color: 'rgba(234, 235, 238, 0.3)'
      paper-toggle-button-unchecked-bar-color: 'rgba(234, 235, 238, 0.18)'
      mdc-checkbox-unchecked-color: 'rgba(234, 235, 238, 0.75)'
      mdc-radio-unchecked-color: 'rgba(234, 235, 238, 0.75)'
      mdc-ripple-hover-opacity: '0.1'
      control-button-background-color: 'rgba(173, 176, 184, 0.2)'
      input-background-color: 'rgba(50, 50, 50, 0.1)'
      input-background-token-color-disabled: 'rgba(50, 50, 50, 0.1)'
      input-fill-color: 'rgba(50,50, 50, 0.1)'
      input-ink-color: 'rgba(234, 235, 238, 0.98)'
      input-label-ink-color: 'rgba(234, 235, 238, 0.98)'
      input-disabled-fill-color: 'rgba(30, 33, 54, 0.5)'
      input-disabled-ink-color: 'rgba(234, 235, 238, 0.45)'
      input-disabled-label-ink-color: 'rgba(234, 235, 238, 0.45)'
      input-idle-line-color: 'transparent'
      input-dropdown-icon-color: 'rgba(234, 235, 238, 0.8)'
      input-hover-line-color: 'rgb(__DARK_RGB_STR__)'
      mdc-select-idle-line-color: 'transparent'
      mdc-text-field-idle-line-color: 'transparent'
      code-editor-background-color: 'rgba(25, 28, 45, 1)'
      codemirror-meta: 'rgba(234, 235, 238, 0.98)'
      codemirror-property: 'rgb(__DARK_RGB_STR__)'
      codemirror-atom: 'rgb(__DARK_RGB_STR__)'
      codemirror-string: 'rgb(164, 209, 255)'
      codemirror-keyword: 'rgb(148, 182, 255)'
      codemirror-number: 'rgb(255, 171, 64)'
      mcg-title-font-weight: '400'
      mush-title-font-weight: '500'
      mush-title-font-size: 'var(--token-size-font-2xl)'
      light-grey-color: 'rgb(103, 104, 119)'
      mush-rgb-grey: '103, 104, 119'
      paper-slider-height: '5px'
      border-radius: '18px'
      
      # --- CARD STYLING ---
      card-mod-card: |
        ha-card { background: transparent; backdrop-filter: none; -webkit-backdrop-filter: none; }
        ha-card::before {
          content: ''; position: absolute; inset: 0;
          background: var(--ha-card-glass-tint, rgba(28, 29, 33, 0.18));
          backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(10px) saturate(1.2));
          z-index: -1; pointer-events: none; border-radius: inherit;
          box-shadow: var(--ha-card-glass-inset-shadow, 3px 3px 0.5px -3.5px rgba(255, 255, 255, 0.15) inset, -2px -2px 0.5px -2px rgba(255, 255, 255, 0.1) inset, 0 0 8px 1px rgba(255, 255, 255, 0.06) inset, 0 0 2px 0 rgba(0, 0, 0, 0.18));
        }
        :host(hui-heading-card) ha-card, :host(hui-glance-card) ha-card { background: none !important; backdrop-filter: none !important; }
        :host(hui-heading-card) ha-card::before, :host(hui-glance-card) ha-card::before { content: none !important; }
        .mdc-data-table { background: none !important; }
        .mdc-data-table__header-cell { background: rgba(30, 33, 54, 0.18) !important; backdrop-filter: var(--ha-card-backdrop-filter) !important; box-shadow: var(--ha-card-glass-inset-shadow) !important; }
        :host(.text-only) ha-card, :host(.text-only) ha-card::before, ha-card.text-only, ha-card.text-only::before { background: none !important; backdrop-filter: none !important; box-shadow: none !important; content: none !important; }
        :host(mushroom-title-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-title-card) ha-card::before { content: none !important; }
        :host(.type-custom-bubble-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; border-radius: 0px !important; }
        :host(.type-custom-bubble-card) ha-card::before { content: none !important; background: none !important; }
        :host(mushroom-chips-card) ha-card { background: none !important; backdrop-filter: none !important; box-shadow: none !important; }
        :host(mushroom-chips-card) ha-card::before { content: none !important; background: none !important; }
        navbar-card { --navbar-background-color: transparent !important; }
        :host(navbar-card) ha-card { background: transparent !important; box-shadow: none !important; }

  # =========================
  # TYPOGRAPHY
  # =========================
  ha-font-family-body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-heading: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-code: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-font-family-longform: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  ha-card-header-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-button-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  mdc-typography-body1-font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  md-list-item-label-text-font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-common-base_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-common-code_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-body1_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-subhead_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-headline_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-caption_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'
  paper-font-title_-_font-family: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'

  ha-font-weight-normal: '400'
  ha-font-weight-medium: '500'
  ha-font-weight-bold: '700'
  ha-font-weight-body: '400'
  ha-font-weight-heading: '500'
  ha-font-weight-action: '500'
  mdc-typography-button-font-weight: '500'
  title-font-weight: 'var(--token-weight-font-title-card)'

  ha-font-size-xs: '10px'
  ha-font-size-s: '12px'
  ha-font-size-m: '14px'
  ha-font-size-l: '15px'
  ha-font-size-xl: '20px'
  ha-font-size-2xl: '25px'
  ha-font-size-3xl: '29px'
  ha-font-size-4xl: '33px'
  ha-font-size-5xl: '42px'
  title-font-size: '20px'
  ha-heading-card-title-font-size: 'var(--token-size-font-l)'
  ha-heading-card-title-font-weight: '500'
  ha-font-smoothing: 'antialiased'
"""
